codedaddies_list/urls.py
from django.contrib import admin
from django.urls import path, include
from my_app import views

urlpatterns = [
    path('', include('my_app.urls')),
    path('admin/', admin.site.urls)
]

my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_search', views.new_search, name='new_search'),
    path('search_history', views.search_history, name='search_history'),
    path('delete_history/<int:history_id>', views.delete_history, name='delete_history'),
    path('delete_all_history', views.delete_all_history, name='delete_all_history'),
    path('goto/<str:search>', views.goto, name='goto'),

        
]

my_app/models.py
from django.db import models

# Create your models here.
class Search(models.Model):
    search = models.CharField(max_length=500)
    # created = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField()

    def __str__(self):
        return self.search

    class Meta:
        verbose_name_plural = 'Searches'

my_app/views.py
import requests
from requests.compat import quote_plus
from django.shortcuts import render
from bs4 import BeautifulSoup
from django.utils import timezone
from . models import Search
from django.http import HttpResponseRedirect

BASE_CGSLIST_URL = 'https://losangeles.craigslist.org/search/?query={}'
BASE_IMAGE_URL = 'https://images.craigslist.org/{}_300x300.jpg'
# Create your views here.
def home(request):
    return render(request, 'my_app/home.html')

def new_search(request):
    search = request.POST.get('search')
    if search:
        time = timezone.now()
        s1=Search.objects.create(search=search,created=time)
    
    final_url = BASE_CGSLIST_URL.format(quote_plus(search))
    no_res = ''
    
    try:
        response = requests.get(final_url)
        data = response.text
        soup =BeautifulSoup(data, features='html.parser')

        post_listings = soup.find_all('li', {'class': 'result-row'})
        
        if soup.find_all('div', {'class': 'alert alert-sm alert-warning'}):
            no_result = soup.find_all('div', {'class': 'alert alert-sm alert-warning'})    
            no_res = "No result found For '{}'. (All words must match)".format(search)
            print(no_result, ' ', no_res)

        final_postings = []

        for post in post_listings:
            post_titles = post.find(class_='result-title').text
            post_url = post.find('a').get('href')
            
            if post.find(class_='result-price'):
                post_price = post.find(class_='result-price').text
            else:
                post_price = 'N/A'

            if post.find(class_='result-image').get('data-ids'):
                post_image = post.find(class_='result-image').get('data-ids').split(',')[0].split(':')[1]
                post_image_url = BASE_IMAGE_URL.format(post_image)
            else:
                post_image_url = 'https://previews.123rf.com/images/urfandadashov/urfandadashov1809/urfandadashov180901275/109135379-photo-not-available-vector-icon-isolated-on-transparent-background-photo-not-available-logo-concept.jpg'
                print(post_image_url)

            final_postings.append((post_titles, post_url, post_price, post_image_url))
        

        stuff_for_front_end = {
            'search' : search,
            'final_postings': final_postings,
            'no_res' :no_res,
        }
    except:
        stuff_for_front_end = { 'errormessage' : 'Check Your Internet Connection'}
    if search:
        s1.save()
    return render(request, 'my_app/new_search.html', stuff_for_front_end)

def search_history(request):
    data = Search.objects.all().order_by('-created')
    stuff_for_front_end = {
        'history' : data,
    }
    return render(request, 'my_app/search_history.html',stuff_for_front_end)


def delete_history(request, history_id):
    Search.objects.get(id=history_id).delete()
    
    return search_history(request)

def delete_all_history(request):
    Search.objects.all().delete()
    return search_history(request)

def goto(request, search):
    if search:
        time = timezone.now()
        s1=Search.objects.create(search=search,created=time)
    
    final_url = BASE_CGSLIST_URL.format(quote_plus(search))
    no_res = ''
    
    try:
        response = requests.get(final_url)
        data = response.text
        soup =BeautifulSoup(data, features='html.parser')

        post_listings = soup.find_all('li', {'class': 'result-row'})
        
        if soup.find_all('div', {'class': 'alert alert-sm alert-warning'}):
            no_result = soup.find_all('div', {'class': 'alert alert-sm alert-warning'})    
            no_res = "No result found For '{}'. (All words must match)".format(search)
            print(no_result, ' ', no_res)

        final_postings = []

        for post in post_listings:
            post_titles = post.find(class_='result-title').text
            post_url = post.find('a').get('href')
            
            if post.find(class_='result-price'):
                post_price = post.find(class_='result-price').text
            else:
                post_price = 'N/A'

            if post.find(class_='result-image').get('data-ids'):
                post_image = post.find(class_='result-image').get('data-ids').split(',')[0].split(':')[1]
                post_image_url = BASE_IMAGE_URL.format(post_image)
            else:
                post_image_url = 'https://previews.123rf.com/images/urfandadashov/urfandadashov1809/urfandadashov180901275/109135379-photo-not-available-vector-icon-isolated-on-transparent-background-photo-not-available-logo-concept.jpg'
                print(post_image_url)

            final_postings.append((post_titles, post_url, post_price, post_image_url))
        

        stuff_for_front_end = {
            'search' : search,
            'final_postings': final_postings,
            'no_res' :no_res,
        }
    except:
        stuff_for_front_end = { 'errormessage' : 'Check Your Internet Connection'}
    if search:
        s1.save()
    return render(request, 'my_app/new_search.html', stuff_for_front_end)

templates/base.html
{% load static %}
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <title>foogle Search</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

<nav>
    <div class="container nav-wrapper" >
        <a href="/" class="brand-logo">FOOGLE Search</a>
        <ul id="nav-mobile" class="right">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'my_app:search_history'%}">Search  history</a></li>
        </ul>
    </div>
</nav>

<div class="container">
{% block content %}

{% endblock content %}
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

templates/my_app/home.html
{% extends 'base.html' %}
{% block content %}

    <h1 style="text-align: center">What do you want to search for ?</h1><br>
    <div class="row">
        <div class="col s4">
            <!-- Promo Content 1 goes here -->
            <div class="center">
                <i class="large material-icons" style="color: #EE6E73">flash_on</i>
                <p>Faster</p>
                <p class="light center">Instant search results ⚡.</p>
            </div>
        </div>

        <div class="col s4">
            <!-- Promo Content 2 goes here -->
            <div class="center">
                <i class="large material-icons" style="color: orange">camera</i>
                <p>Filter your searches</p>
                <p class="light center">Functionality to filter based on pricing.</p>
            </div>
        </div>

        <div class="col s4">
            <!-- Promo Content 3 goes here -->
            <div class="center">
                <i class="large material-icons" style="color:#42a5f5">chrome_reader_mode</i>
                <p>Attractive GUI</p>
                <p class="light center">Built this with ❤️</p>
            </div>
        </div>
    </div>

<form action="{% url 'my_app:new_search' %}" method="post">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Type here................" >
     <center><button class="btn waves-effect waves-light" type="submit" name="action">Search
        <i class="material-icons right">search</i>
    </button>
    </center>
</form>
{% endblock content %}

templates/my_app/new_search.html
{% extends 'base.html'%}
{% csrf_token %}    
{% block content %}
    <h2 style="text-align: center">{{ search | title }}</h2>
  {% if errormessage %}
  <script>alert('{{ errormessage }}');</script>
  {% endif %}
  {% if no_res %}
  <h4 style="text-align: center">{{ no_res | title }}</h4>
  {% endif %}
    <div class="row">
    {% for post in final_postings %}
    
    <div class="col s4">
      <div class="card">
      <a href="{{ post.1 }}">
        <div class="card-image">
          <img src="{{ post.3 }}" href="{{ post.1 }}">
        </div>
        </a>
        <div class="card-content">
          <p>{{ post.0 }}</p>
        </div>
        <div class="card-action">
          <a href="{{ post.1 }}">Price : {{ post.2 }}</a>
        </div>
      </div>
    </div>
    
    {% endfor %}
    </div>
    
  
    {% endblock content %}

templates/my_app/search_history.html
{% extends 'base.html' %}
{% csrf_token %}
{% block content %}


<h3 style='text-align: center'>Search History </h3>
{% if history %}

<form action="delete_all_history" method="post">
    {% csrf_token %}
        <div class="right-align">
            <button class="btn waves-effect waves-light red" type="submit" name="action">Delete ALL
            <i class="material-icons right">delete_forever</i>
            </button>
        </div>
</form>    
        
    <div class="collection">
        {% for data in history %}
            <a href="goto/{{ data.search }}" class="collection-item">
                <span class="badge">
                    <form action="delete_history/{{ data.id }}" method="post">
                    {% csrf_token %}
                        <button class="btn waves-effect waves-light btn-small red" type="submit" name="action">Delete
                            <i class="material-icons right">delete_forever</i>
                        </button>
                    </form>
                </span>
                <span class="badge">{{ data.created }}</span>{{ data.search }}
            </a>
        {% endfor %}
    </div>
{% else %}
<div class="center-align">
<i class="large material-icons center" style="color: green">restore</i>
<h5>Go see the sites! The pages you visit will show up here..</h5>
</div>
{% endif %}
    
{% endblock content %}